# Generated by Django 4.0.4 on 2022-04-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('User_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=8)),
                ('Email_address', models.EmailField(blank=True, max_length=50, unique=True)),
            ],
        ),
    ]
